server: 
 port: ${server_port}

spring:
 application:
   name: msvc-auth
 jwt:
   expiration: ${JWT_EXPIRATION}
   secret: ${JWT_SECRET}
 datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
 redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
 jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
 rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USER}
    password: ${RABBIT_PASSWORD}
  