server:
  port: ${SERVER_PORT}

spring:
  application:
    name: msvc-notification
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USER}
    password: ${RABBIT_PASSWORD}
