server:
  port: ${SERVER_PORT}
spring:
  application:
    name: msvc-eureka
eureka:
  instance:
    hostname: ${EUREKA_HOST}
  client:
    fetchRegistry: 'false'
    registerWithEureka: 'false'
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    renewal-percent-threshold: 0.85



spring:
  application:
    name: msvc-auth
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.5